source ~/.tmux/colors.conf

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g status-position top
set -g status-left-length 20
set -g status-right ""
set -s escape-time 0
set -g repeat-time 0
set -g history-limit 50000
set -g display-time 3000
set -g status-keys emacs
set -g focus-events on
setw -g aggressive-resize on

set -g terminal-features "alacritty:RGB"
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g prefix C-a
bind C-a send-prefix

bind & kill-window
bind x kill-pane

bind | split-window -h
bind - split-window -v

bind r source-file ~/.tmux.conf \; display-message "Sourced ~/.tmux.conf"

bind Enter copy-mode

bind -r a last-window
bind -r C-h previous-window
bind -r C-l next-window

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2
bind -r H resize-pane -L 2
