general {
    lock_cmd = hyprlock
    unlock_cmd = pkill -USR1 hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 300 # 5 min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600 # 10 min
    on-timeout = systemctl suspend
}
