format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$python\
$character
"""

[directory]
read_only = " "

[python]
format = "[(\\($virtualenv\\) )]($style)"
