set -g message-style "fg={{colors.outline.default.hex}}"
set -g status-style "fg={{colors.outline.default.hex}}"

set -g window-status-style "fg={{colors.outline_variant.default.hex}}"
set -g window-status-current-style "fg={{colors.primary.default.hex}},bold"

set -g pane-border-style "fg={{colors.outline_variant.default.hex}}"
set -g pane-active-border-style "fg={{colors.primary.default.hex}}"
set -g display-panes-color "{{colors.outline_variant.default.hex}}"
set -g display-panes-active-color "{{colors.primary.default.hex}}"
set -g popup-border-style "fg={{colors.primary.default.hex}}"

set -g mode-style "fg={{colors.on_primary.default.hex}},bg={{colors.primary.default.hex}}"
set -g menu-border-style "fg={{colors.outline_variant.default.hex}}"
set -g menu-selected-style "fg={{colors.on_primary.default.hex}},bg={{colors.primary.default.hex}}"

setw -g clock-mode-color "{{colors.primary.default.hex}}"
